### ISSUE TITLE
CollectionView support

### ISSUE THREAD

**Issue by mschonvogel** [quemb/QMBParallaxScrollViewController#5]
I would like to use a UICollectionViewController as a bottomController but it is getting its own scrollbar. Do you have any idea on how to fix that / can you provide an example with a collection view?

![bildschirmfoto 2014-01-30 um 17 52 03](https://f.cloud.github.com/assets/370839/2042310/80065b3a-89cf-11e3-8c03-af54a9a3e29d.png)

**Comment by tonimoeckel** [comment]
Yes that's strange... I had a similar problem with an UITableView and fixed it in the current develop Branch. What I did to fix this was setting up an observer for the contentSize Property of the ScrollView. Have a look a the develop branch: https://github.com/quemb/QMBParallaxScrollViewController/tree/develop 
This should also work with Collection Views....

**Comment by mschonvogel** [comment]
@tonimoeckel Thanks, that worked for me! :+1: 
One more thing: Normally, tableviews/collectionviews are reusing cells which are out of the viewport. I discovered that with your parallaxScrollViewController, all cells are instantiated immediately and won't be reused. Do you know a way to fix that?

**Comment by tonimoeckel** [comment]
Yeah you are right, this is definitely a big performance issue. It's not possible with the current layout of the parallax scrollview. I don't see and proper solution for this right now. Sry...
